# Generated by Django 6.0.7 on 2026-08-11 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6, unique=True, verbose_name='PIN')),
                ('status', models.CharField(choices=[('WAITING', 'En espera'), ('ACTIVE', 'En curso'), ('FINISHED', 'Finalizada')], default='WAITING', max_length=10, verbose_name='Estado')),
                ('current_question', models.PositiveIntegerField(default=0, verbose_name='Pregunta actual')),
                ('revealed', models.BooleanField(default=False, verbose_name='Respuesta revelada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada el')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada el')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Anfitrión')),
            ],
            options={
                'verbose_name': 'Sesión en vivo',
                'verbose_name_plural': 'Sesiones en vivo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Puntos')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Se unió el')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_participations', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quizzes.livesession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['-score', 'joined_at'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivias', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Trivia',
                'verbose_name_plural': 'Trivias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('option_a', models.CharField(max_length=255, verbose_name='Opción A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Opción B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Opción C')),
                ('option_d', models.CharField(max_length=255, verbose_name='Opción D')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Respuesta correcta')),
                ('points', models.PositiveIntegerField(default=100, verbose_name='Puntos')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.trivia', verbose_name='Trivia')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='quizzes.trivia', verbose_name='Trivia'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Puntos obtenidos')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Puntos totales')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada el')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.trivia', verbose_name='Trivia')),
            ],
            options={
                'verbose_name': 'Intento',
                'verbose_name_plural': 'Intentos',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Opción elegida')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Correcta?')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Puntos ganados')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Respondida el')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.liveparticipant', verbose_name='Participante')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta en vivo',
                'verbose_name_plural': 'Respuestas en vivo',
                'unique_together': {('participant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Opción elegida')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Correcta?')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Puntos ganados')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.attempt', verbose_name='Intento')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
