# Generated by Django 6.0.7 on 2026-08-11 23:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Respondida el'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quizzes.question', verbose_name='Pregunta actual'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pregunta mostrada el'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pregunta mostrada el'),
        ),
        migrations.AddField(
            model_name='trivia',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Segundos disponibles para responder cada pregunta. Cuanto más rápido respondas, más puntos ganas.', verbose_name='Tiempo por pregunta (segundos)'),
        ),
    ]
